export const categories = [
  "Actions",
  "Data display",
  "Navigation",
  "Feedback",
  "Data input",
  "Layout",
  "Mockup",
] as const;
export type CatalogCategory = (typeof categories)[number];
export interface CatalogEntry {
  id: string;
  name: string;
  category: CatalogCategory;
  api: string;
  description: string;
  code: string;
  source: string;
}
type Row = [string, string, CatalogCategory, string, string, string];
// Snapshot of all 68 public daisyUI component families, checked 2026-09-30.
const rows: Row[] = [
  [
    "button",
    "Button",
    "Actions",
    "Button",
    "Clear actions, quiet secondary choices and explicit destructive states.",
    "<Button onClick={runScan}>Run scan</Button>",
  ],
  [
    "dropdown",
    "Dropdown",
    "Actions",
    "Dropdown",
    "An action menu with arrow keys, Escape and outside dismissal.",
    '<Dropdown label="Actions" items={[{ id: "export", label: "Export", onSelect: exportReport }]} />',
  ],
  [
    "fab",
    "FAB / Speed Dial",
    "Actions",
    "Fab",
    "A compact action launcher. Position it in your application shell.",
    '<Fab label="Create" actions={actions} />',
  ],
  [
    "modal",
    "Modal",
    "Actions",
    "Modal",
    "A native dialog with a contained focus sequence and an inert background.",
    '<Modal open={open} onOpenChange={setOpen} title="Review scope">\n  <p>Confirm the authorized assets.</p>\n</Modal>',
  ],
  [
    "swap",
    "Swap",
    "Actions",
    "Swap",
    "One accessible toggle, two visual states.",
    '<Swap label="Mute notifications" on="Muted" off="Sound on" />',
  ],
  [
    "theme-controller",
    "Theme Controller",
    "Actions",
    "ThemeController",
    "Let light into the same glass using the enclosing ThemeProvider.",
    "<ThemeProvider>\n  <ThemeController />\n</ThemeProvider>",
  ],
  [
    "accordion",
    "Accordion",
    "Data display",
    "Accordion",
    "Native grouped disclosures keep only one answer open.",
    '<Accordion items={[{ id: "scope", title: "What is in scope?", content: "Approved domains." }]} />',
  ],
  [
    "avatar",
    "Avatar",
    "Data display",
    "Avatar",
    "A photo or initials, with a fallback for failed image loads.",
    '<Avatar name="Alex Morgan" size="lg" />',
  ],
  [
    "aura",
    "Aura",
    "Data display",
    "Aura",
    "A restrained cyan and violet border light for one important surface.",
    "<Aura><Card><CardContent>Priority review</CardContent></Card></Aura>",
  ],
  [
    "badge",
    "Badge",
    "Data display",
    "Badge",
    "Named severity states that remain understandable without color.",
    '<Badge severity="high">High severity</Badge>',
  ],
  [
    "card",
    "Card",
    "Data display",
    "Card",
    "Composable glass surfaces for headings, content and actions.",
    "<Card>\n  <CardHeader><CardTitle>Surface</CardTitle></CardHeader>\n  <CardContent>32 subdomains</CardContent>\n</Card>",
  ],
  [
    "carousel",
    "Carousel",
    "Data display",
    "Carousel",
    "Manually explore slides without autoplay or unexpected movement.",
    '<Carousel label="Reports" items={slides} />',
  ],
  [
    "chat",
    "Chat bubble",
    "Data display",
    "ChatBubble",
    "Message, author and time, with incoming and outgoing alignment.",
    '<ChatBubble author="Analyst" time="10:42">Scope verified.</ChatBubble>',
  ],
  [
    "collapse",
    "Collapse",
    "Data display",
    "Collapse",
    "A native disclosure for supporting details.",
    '<Collapse title="Evidence">Certificate matches the approved domain.</Collapse>',
  ],
  [
    "countdown",
    "Countdown",
    "Data display",
    "Countdown",
    "A bounded number display; your application owns the clock.",
    '<Countdown value={remainingSeconds} label="Seconds" />',
  ],
  [
    "diff",
    "Diff",
    "Data display",
    "Diff",
    "Compare two visual surfaces with a keyboard operable slider.",
    '<Diff before={<Before />} after={<After />} label="Reveal comparison" />',
  ],
  [
    "hover-3d",
    "Hover 3D Card",
    "Data display",
    "HoverCard",
    "Subtle pointer tilt that follows the motion preference.",
    "<HoverCard><Card><CardContent>Glass surface</CardContent></Card></HoverCard>",
  ],
  [
    "hover-gallery",
    "Hover Gallery",
    "Data display",
    "HoverGallery",
    "Mouse previews with explicit buttons for touch and keyboard.",
    '<HoverGallery label="Reports" items={slides} />',
  ],
  [
    "kbd",
    "Kbd",
    "Data display",
    "Kbd",
    "Readable keyboard instructions and shortcuts.",
    "<span><Kbd>Ctrl</Kbd> + <Kbd>K</Kbd></span>",
  ],
  [
    "list",
    "List",
    "Data display",
    "List",
    "A compact sequence of assets or work items.",
    "<List><li>api.example.com</li><li>mail.example.com</li></List>",
  ],
  [
    "stat",
    "Stat",
    "Data display",
    "Stat",
    "A single measurement with an optional trend.",
    '<Stat label="Live hosts" value={30} delta="8%" trend="up" />',
  ],
  [
    "status",
    "Status",
    "Data display",
    "Status",
    "A small status point always paired with a text label.",
    '<Status tone="success" label="Connected" />',
  ],
  [
    "table",
    "Table",
    "Data display",
    "Table",
    "Native tabular semantics inside a horizontally scrollable surface.",
    '<Table>\n  <caption>Assets</caption>\n  <thead><tr><th scope="col">Host</th></tr></thead>\n  <tbody><tr><td>api.example.com</td></tr></tbody>\n</Table>',
  ],
  [
    "text-rotate",
    "Text Rotate",
    "Data display",
    "TextRotate",
    "Rotating text with pause, hover suspension and motion opt-out.",
    '<TextRotate items={["Discover.", "Understand.", "Protect."]} />',
  ],
  [
    "timeline",
    "Timeline",
    "Data display",
    "Timeline",
    "Chronological events with optional machine readable dates.",
    '<Timeline items={[{ id: "1", time: "10:42", title: "Scan completed", description: "30 hosts analyzed." }]} />',
  ],
  [
    "breadcrumbs",
    "Breadcrumbs",
    "Navigation",
    "Breadcrumbs",
    "A linked location trail with the current page identified.",
    '<Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Assets" }]} />',
  ],
  [
    "dock",
    "Dock",
    "Navigation",
    "Dock",
    "A compact navigation bar ready for your bottom application region.",
    '<Dock label="Workspace" items={links} activeId="assets" />',
  ],
  [
    "link",
    "Link",
    "Navigation",
    "Link",
    "An underlined anchor with native navigation behavior.",
    '<Link href="/reports">View reports</Link>',
  ],
  [
    "megamenu",
    "Megamenu",
    "Navigation",
    "MegaMenu",
    "Grouped navigation in a responsive disclosure.",
    '<MegaMenu label="Explore" groups={[{ title: "Workspace", items: links }]} />',
  ],
  [
    "menu",
    "Menu",
    "Navigation",
    "Menu",
    "Vertical or horizontal links with current and unavailable states.",
    '<Menu label="Workspace" items={links} activeId="assets" />',
  ],
  [
    "navbar",
    "Navbar",
    "Navigation",
    "Navbar",
    "Brand, navigation and actions in a wrapping header.",
    '<Navbar brand="Hydra" actions={<Button>New scan</Button>}>Workspace</Navbar>',
  ],
  [
    "pagination",
    "Pagination",
    "Navigation",
    "Pagination",
    "Bounded navigation that stays compact even with many pages.",
    "<Pagination page={page} totalPages={12} onPageChange={setPage} />",
  ],
  [
    "steps",
    "Steps",
    "Navigation",
    "Steps",
    "A process with explicit completed and current steps.",
    '<Steps steps={["Scope", "Review", "Run"]} current={1} />',
  ],
  [
    "tab",
    "Tabs",
    "Navigation",
    "Tabs",
    "Linked panels with roving focus and arrow key navigation.",
    '<Tabs label="Asset details" items={[{ id: "info", label: "Overview", content: "Asset summary" }]} />',
  ],
  [
    "alert",
    "Alert",
    "Feedback",
    "Alert",
    "Persistent notices with named severity and appropriate announcements.",
    '<Alert tone="warning" title="Review required">Confirm scope before scanning.</Alert>',
  ],
  [
    "loading",
    "Loading",
    "Feedback",
    "Loading",
    "Spinner, dots or bars with a visible loading description.",
    '<Loading label="Resolving hosts" variant="dots" />',
  ],
  [
    "progress",
    "Progress",
    "Feedback",
    "Progress",
    "A linear measurement with a label and bounded percentage.",
    '<Progress value={68} label="Discovery" />',
  ],
  [
    "radial-progress",
    "Radial progress",
    "Feedback",
    "RadialProgress",
    "A compact circular progress readout.",
    '<RadialProgress value={72} label="Review completion" />',
  ],
  [
    "skeleton",
    "Skeleton",
    "Feedback",
    "Skeleton",
    "A placeholder that respects the reduced motion setting.",
    '<Skeleton label="Loading asset summary" className="h-24" />',
  ],
  [
    "toast",
    "Toast",
    "Feedback",
    "Toast",
    "A dismissible announcement; your application controls its lifetime.",
    '<Toast tone="success" onDismiss={dismiss}>Preferences saved.</Toast>',
  ],
  [
    "tooltip",
    "Tooltip",
    "Feedback",
    "Tooltip",
    "Supplementary text on hover or focus; Escape dismisses it.",
    '<Tooltip content="Download a local JSON report"><Button>Export</Button></Tooltip>',
  ],
  [
    "calendar",
    "Calendar",
    "Data input",
    "Calendar",
    "Single date selection, month navigation, date bounds and grid keyboard control.",
    '<Calendar label="Review date" value={date} onValueChange={setDate} min="2026-01-01" />',
  ],
  [
    "checkbox",
    "Checkbox",
    "Data input",
    "Checkbox",
    "A labeled native checkbox with an optional description.",
    '<Checkbox label="Validate findings" defaultChecked />',
  ],
  [
    "fieldset",
    "Fieldset",
    "Data input",
    "Fieldset",
    "A native group that can disable all its controls at once.",
    '<Fieldset legend="Monitoring"><Checkbox label="Email summaries" /></Fieldset>',
  ],
  [
    "file-input",
    "File Input",
    "Data input",
    "FileInput",
    "A native file picker. Selection does not upload anything.",
    '<FileInput label="Asset list" accept=".csv,.json" />',
  ],
  [
    "filter",
    "Filter",
    "Data input",
    "Filter",
    "Select one filter, then reset to expose the other choices.",
    '<Filter label="Severity" options={options} value={filter} onValueChange={setFilter} />',
  ],
  [
    "label",
    "Label",
    "Data input",
    "Label",
    "An explicit label for an existing input identifier.",
    '<Label htmlFor="organization">Organization</Label>\n<Input id="organization" />',
  ],
  [
    "radio",
    "Radio",
    "Data input",
    "Radio",
    "Mutually exclusive native form choices.",
    '<Radio name="profile" value="passive" label="Passive" defaultChecked />',
  ],
  [
    "range",
    "Range slider",
    "Data input",
    "RangeInput",
    "A labeled native range for pointer, touch and keyboard.",
    '<RangeInput label="Concurrency" min={1} max={10} value={value} onChange={e => setValue(Number(e.target.value))} />',
  ],
  [
    "rating",
    "Rating",
    "Data input",
    "Rating",
    "A native radio group represented by stars.",
    '<Rating label="Evidence quality" value={rating} onValueChange={setRating} />',
  ],
  [
    "select",
    "Select",
    "Data input",
    "Select",
    "A native select with shared label and error wiring.",
    '<Field label="Profile"><Select><option>Passive</option><option>Active</option></Select></Field>',
  ],
  [
    "input",
    "Text Input",
    "Data input",
    "Input",
    "Text entry with shared field hints and invalid state wiring.",
    '<Field label="Scan target" hint="Domain without protocol"><Input placeholder="example.com" /></Field>',
  ],
  [
    "textarea",
    "Textarea",
    "Data input",
    "Textarea",
    "Multiline context with native resizing and validation.",
    '<Field label="Notes"><Textarea placeholder="Investigation context…" /></Field>',
  ],
  [
    "toggle",
    "Toggle",
    "Data input",
    "Switch",
    "An accessible labeled switch for an immediate preference.",
    '<Switch label="Continuous monitoring" defaultChecked />',
  ],
  [
    "validator",
    "Validator",
    "Data input",
    "Validator",
    "Native form constraints with visual validation feedback.",
    '<Validator onValidSubmit={save}>\n  <Field label="Email"><Input name="email" type="email" required /></Field>\n  <Button type="submit">Save</Button>\n</Validator>',
  ],
  [
    "otp",
    "OTP",
    "Data input",
    "OtpInput",
    "One native input preserves paste, editing and one-time-code autofill.",
    '<OtpInput label="Verification code" length={6} required />',
  ],
  [
    "divider",
    "Divider",
    "Layout",
    "Divider",
    "Horizontal and vertical separation, with optional supporting text.",
    "<Divider>or continue with</Divider>",
  ],
  [
    "drawer",
    "Drawer sidebar",
    "Layout",
    "Drawer",
    "A left or right native dialog for temporary secondary navigation.",
    '<Drawer open={open} onOpenChange={setOpen} title="Workspace" side="right">\n  <Menu items={links} />\n</Drawer>',
  ],
  [
    "footer",
    "Footer",
    "Layout",
    "Footer",
    "Simple, complete and expressive footer compositions.",
    '<Footer variant="simple" copyright="Hydra Security" />',
  ],
  [
    "hero",
    "Hero",
    "Layout",
    "Hero",
    "A stained-glass introduction with optional artwork and actions.",
    '<Hero title="Clarity beyond the horizon." description="See your external surface." artwork={<RoseWindow />} />',
  ],
  [
    "indicator",
    "Indicator",
    "Layout",
    "Indicator",
    "A corner marker for counts or status.",
    '<Indicator indicator={<Badge>3</Badge>}><Avatar name="Alex Morgan" /></Indicator>',
  ],
  [
    "join",
    "Join (group items)",
    "Layout",
    "Join",
    "Connected controls in horizontal or vertical arrangements.",
    '<Join><Button variant="outline">Day</Button><Button variant="outline">Week</Button></Join>',
  ],
  [
    "mask",
    "Mask",
    "Layout",
    "Mask",
    "Circle, hexagon, diamond or squircle clipping for noninteractive artwork.",
    '<Mask shape="hexagon"><RoseWindow /></Mask>',
  ],
  [
    "stack",
    "Stack",
    "Layout",
    "Stack",
    "A shallow stack for decorative, noninteractive surfaces.",
    '<Stack><Card>Latest report</Card><Card aria-hidden="true">Previous</Card></Stack>',
  ],
  [
    "mockup-browser",
    "Browser mockup",
    "Mockup",
    "BrowserMockup",
    "A browser frame with a display-only address bar.",
    '<BrowserMockup url="hydra.example.com"><p>Workspace preview</p></BrowserMockup>',
  ],
  [
    "mockup-code",
    "Code mockup",
    "Mockup",
    "CodeMockup",
    "Escaped, selectable code inside a scrollable frame.",
    '<CodeMockup language="bash" code="npm install @hydra-security/ui" />',
  ],
  [
    "mockup-phone",
    "Phone mockup",
    "Mockup",
    "PhoneMockup",
    "A compact device frame for responsive compositions.",
    '<PhoneMockup><Status label="Surface monitored" /></PhoneMockup>',
  ],
  [
    "mockup-window",
    "Window mockup",
    "Mockup",
    "WindowMockup",
    "A desktop window frame for application previews.",
    '<WindowMockup title="Hydra workspace"><p>Scan complete.</p></WindowMockup>',
  ],
];
export const catalog: CatalogEntry[] = rows.map(
  ([id, name, category, api, description, code]) => ({
    id,
    name,
    category,
    api,
    description,
    code,
    source: `https://daisyui.com/components/${id}/`,
  }),
);
