// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {AssetInventory,validateInventory,type InventoryAsset} from './components/asset-inventory';
afterEach(cleanup);
const assets:InventoryAsset[]=[{id:'a',label:'api.example.com',kind:'subdomain',risk:'high',ownership:'unverified',source:'Certificate transparency',evidence:'Example certificate SAN',lastSeen:'2026-09-19T10:00:00.000Z'},{id:'b',label:'example.com',kind:'domain',risk:'unknown',ownership:'confirmed',source:'User scope',evidence:'Scope declaration',lastSeen:'2026-09-19T10:00:00.000Z'}];
it('combines search, type, risk and ownership filters without mutating inventory',()=>{render(<AssetInventory assets={assets}/>);fireEvent.change(screen.getByLabelText('Search assets'),{target:{value:' CERTIFICATE '}});fireEvent.change(screen.getByLabelText('Asset type'),{target:{value:'subdomain'}});fireEvent.change(screen.getByLabelText('Risk'),{target:{value:'high'}});fireEvent.change(screen.getByLabelText('Ownership'),{target:{value:'unverified'}});expect(screen.getByRole('status')).toHaveTextContent('1 of 2 assets');fireEvent.change(screen.getByLabelText('Risk'),{target:{value:'low'}});expect(screen.getByText('No assets match these filters.')).toBeInTheDocument();expect(assets).toHaveLength(2);});
it('shows evidence and attribution, invokes selection and closes details',()=>{const select=vi.fn();render(<AssetInventory assets={assets} onSelect={select}/>);fireEvent.click(screen.getByRole('button',{name:'api.example.com'}));expect(select).toHaveBeenCalledWith(assets[0]);expect(screen.getByText('Example certificate SAN')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Close asset details'}));expect(screen.queryByText('Example certificate SAN')).not.toBeInTheDocument();});
it.each([{risk:'safe'},{ownership:'owned'},{lastSeen:'2026-02-30T00:00:00.000Z'},{lastSeen:'yesterday'},{source:''},{evidence:42}])('rejects invalid metadata %j',value=>{expect(validateInventory([{...assets[0],...value}]).length).toBeGreaterThan(0);});
it('reports invalid runtime data and duplicate IDs',()=>{expect(validateInventory([assets[0],assets[0]])).not.toEqual([]);render(<AssetInventory assets={null as unknown as InventoryAsset[]}/>);expect(screen.getByRole('alert')).toHaveTextContent('Invalid inventory data');});
it('renders supplied evidence as text',()=>{render(<AssetInventory assets={[{...assets[0],evidence:'<script>alert(1)</script>'}]}/>);fireEvent.click(screen.getByRole('button',{name:'api.example.com'}));expect(screen.getByText('<script>alert(1)</script>')).toBeInTheDocument();expect(document.querySelector('script')).toBeNull();});
