import ts from "typescript";
import { readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";

const root = resolve("."),
  config = ts.readConfigFile("packages/ui/tsconfig.json", ts.sys.readFile);
if (config.error)
  throw Error(ts.flattenDiagnosticMessageText(config.error.messageText, "\n"));
const parsed = ts.parseJsonConfigFileContent(
  config.config,
  ts.sys,
  resolve("packages/ui"),
);
const program = ts.createProgram(parsed.fileNames, parsed.options),
  checker = program.getTypeChecker();
const entry = program.getSourceFile(resolve("packages/ui/src/index.ts"));
const nativeKeys = new Set([
  "children",
  "className",
  "id",
  "name",
  "value",
  "defaultValue",
  "disabled",
  "readOnly",
  "required",
  "placeholder",
  "type",
  "onChange",
  "aria-label",
]);
const own = (node) =>
  node
    ?.getSourceFile()
    .fileName.replaceAll("\\", "/")
    .includes("/packages/ui/src/");
const text = (node) => node.getText().replace(/\s+/g, " ");
const api = {};
for (const exported of checker.getExportsOfModule(
  checker.getSymbolAtLocation(entry),
)) {
  const name = exported.name;
  if (!/^[A-Z]/.test(name)) continue;
  const symbol =
    exported.flags & ts.SymbolFlags.Alias
      ? checker.getAliasedSymbol(exported)
      : exported;
  if (!(symbol.flags & ts.SymbolFlags.Value)) continue;
  const declaration = symbol.valueDeclaration ?? symbol.declarations?.[0];
  if (!declaration || !own(declaration)) continue;
  const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
  const signature =
    type.getCallSignatures()[0] ?? type.getConstructSignatures()[0];
  if (!signature) continue;
  const parameter = signature.getParameters()[0];
  if (!parameter) continue;
  const props = checker.getTypeOfSymbolAtLocation(parameter, declaration);
  let fn = ts.isFunctionDeclaration(declaration) ? declaration : undefined;
  if (
    ts.isVariableDeclaration(declaration) &&
    declaration.initializer &&
    ts.isCallExpression(declaration.initializer)
  )
    fn = declaration.initializer.arguments.find(
      (arg) => ts.isArrowFunction(arg) || ts.isFunctionExpression(arg),
    );
  const defaults = {};
  const binding = fn?.parameters[0]?.name;
  if (binding && ts.isObjectBindingPattern(binding))
    for (const element of binding.elements)
      if (element.initializer)
        defaults[element.propertyName?.getText() ?? element.name.getText()] =
          text(element.initializer);
  // Locale defaults are resolved after the hook; keep their source key visible.
  for (const match of (fn?.body?.getText() ?? "").matchAll(
    /if\s*\(\s*(\w+)\s*===\s*undefined\s*\)\s*\1\s*=\s*messages\.(\w+);/g,
  ))
    defaults[match[1]] = "locale." + match[2];
  for (const match of (fn?.body?.getText() ?? "").matchAll(
    /(\w+)\s*===\s*undefined\s*\?\s*messages\.(\w+)/g,
  ))
    defaults[match[1]] = "locale." + match[2];
  for (const match of (fn?.body?.getText() ?? "").matchAll(
    /(\w+)\s*\?\?=\s*inheritedLocale/g,
  ))
    defaults[match[1]] = "LocaleProvider.locale";
  {
    const visit = (node) => {
      if (
        ts.isPropertyAssignment(node) &&
        node.name.getText() === "defaultVariants" &&
        ts.isObjectLiteralExpression(node.initializer)
      )
        for (const p of node.initializer.properties)
          if (ts.isPropertyAssignment(p))
            defaults[p.name.getText()] = text(p.initializer);
      ts.forEachChild(node, visit);
    };
    visit(declaration.getSourceFile());
  }
  const all = checker.getPropertiesOfType(props);
  const rows = all
    .filter(
      (p) =>
        p.declarations?.some(own) ||
        nativeKeys.has(p.name) ||
        ["variant", "size"].includes(p.name),
    )
    .map((p) => ({
      name: p.name,
      type: checker
        .typeToString(
          checker.getTypeOfSymbolAtLocation(p, declaration),
          declaration,
          ts.TypeFormatFlags.NoTruncation,
        )
        .replace(/import\("[^"]+"\)\./g, ""),
      required: !(p.flags & ts.SymbolFlags.Optional),
      default: defaults[p.name] ?? null,
      description: ts.displayPartsToString(p.getDocumentationComment(checker)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, "en"));
  api[name] = {
    source: relative(root, declaration.getSourceFile().fileName),
    description: ts.displayPartsToString(
      symbol.getDocumentationComment(checker),
    ),
    native: all.length > rows.length,
    props: rows,
  };
}
const sorted = Object.fromEntries(
  Object.entries(api).sort(([a], [b]) => a.localeCompare(b, "en")),
);
const escape = (value) =>
  String(value)
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ")
    .replaceAll("`", "&#96;");
const markdown = [
  "# Public component API",
  "",
  "Generated from TypeScript by `npm run docs:api`. Do not edit this file manually.",
  "Component props and common native props are listed. Native components also accept their React HTML attributes; consult the exported types for the complete contract.",
  "Defaults named `locale.*` come from `LocaleProvider`. Values and option content belong to the application.",
  "For behavioral states see [component contracts](component-contracts.md), [foundations](foundations.md) and [data controls](data-controls.md).",
  "",
];
for (const [name, item] of Object.entries(sorted)) {
  markdown.push(
    "## " + name,
    "",
    `[Source](../${item.source})`,
    item.description,
    "",
    "| Prop | Type | Required | Default | Description |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const prop of item.props)
    markdown.push(
      `| ${escape(prop.name)} | \`${escape(prop.type)}\` | ${prop.required ? "yes" : "no"} | ${escape(prop.default ?? "—")} | ${escape(prop.description)} |`,
    );
  if (item.native)
    markdown.push("", "Also accepts native React HTML attributes.");
  markdown.push("");
}
const outputs = [
  [
    "apps/showcase/src/component-api.generated.json",
    JSON.stringify(sorted, null, 2) + "\n",
  ],
  ["docs/api.md", markdown.join("\n").trimEnd() + "\n"],
];
for (const [path, content] of outputs) {
  if (process.argv.includes("--check")) {
    const existing = await readFile(path, "utf8").catch(() => null);
    if (existing !== content)
      throw Error(
        path + " is stale; run npm run docs:api and commit the result.",
      );
  } else await writeFile(path, content);
}
console.log(
  `${Object.keys(sorted).length} public component APIs ${process.argv.includes("--check") ? "verified" : "generated"}.`,
);
